name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Java 17 instead of Java 11
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    # Grant execute permission for Gradlew
    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    # Clear Gradle Cache (Optional but recommended for fresh builds)
    - name: Clear Gradle Cache
      run: rm -rf ~/.gradle/caches/

    # Build the APK
    - name: Build APK
      run: ./gradlew assembleDebug

    # Upload the built APK
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
